name: MadeByMe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  flutter_stripe: ^10.0.0
  in_app_purchase: 3.2.0
  intl: ^0.17.0
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  firebase_storage: ^12.3.5
  firebase_database: ^11.1.5
  firebase_analytics: ^11.3.4
  image_picker: ^0.8.6
  path: ^1.8.3
  shared_preferences: ^2.3.3
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true  # This line enables Material icons
  assets:
    - lib/assets/config/vision_service_account.json
